### ISSUE TITLE
🍅 [TODO] 2024-08-25

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#1]
점심으로 토마토 스파게티 먹어서 토마토

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅

### Hackathon
- [x] 23일 회의 변경 사항(울음소리 분석 -> 챗봇) 기술 명세
- [x] 사용 기술 리스트화
- [x] Infra Architecture 고민해보기

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] [게시물 목록 조회 API](https://github.com/INgandle/social-feed-hub/issues/12)
- [x] [게시물 상세 조회 API](https://github.com/INgandle/social-feed-hub/issues/13)

### etc.
- [x] SQLD 후기 대충 어딘가에 작성하기
- [x] 깃허브 블로그 설정
- [x] [Impossible](https://www.youtube.com/watch?v=Kg6aD8EGcKw) 질릴때까지 듣기
