### ISSUE TITLE
🍪 [TODO] 2024-09-03

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#10]
촉.초 먹는중

## Schedule

- **`13:00 ~ 14:00` 프리온보딩 인턴십 회의 (오프라인)**
- **`14:00 ~ 17:00` 프리온보딩 인턴십 강의 (오프라인)**
- **`17:30 ~ 18:00` SWTH PT 멘토링 (온라인, 줌)**
- **`20:30 ~ 21:00` KDTH 매니저님과 팀 미팅 (온라인, 줌)**
- **`21:00 ~ 00:30` KDTH 기획 회의 (온라인, 젭)**

### Routine
- [ ] 알고리즘 1시간
- [x] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- 과제
  - [x] 리뷰 생성 API 서비스 테스트 코드
  - [ ] 사용자 설정 업데이트 API 테스트코드
  - [ ] 사용자 정보 조회 API 테스트코드

### etc.
- [ ] 프리온보딩 프론트엔드 챌린지 사전 미션 [(영상)](https://www.youtube.com/watch?v=8aGhZQkoFbQ)
- [x] 이동 시간 활용해 [책](https://product.kyobobook.co.kr/detail/S000001033125) 읽기
