### ISSUE TITLE
😪 [TODO] 2024-09-04

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#11]
14시간 잠;;

## Schedule

- **`19:30 ~ 20:00` KDTH 매니저님과 팀 미팅 (온라인, 줌)**
- **`20:00 ~ 23:00` 프리온보딩 백엔드 챌린지 9월 (온라인, 줌)**
- **`22:00 ~ 23:40` 프리온보딩 인턴십 과제분석 (온라인, 디스코드)**
- **`24:30 ~ 26:40` KDTH 개발 회의 (온라인, 젭)**

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- [x] 회의 전에 과제 정독하기
- 이전 과제
  - [ ] 사용자 설정 업데이트 API 테스트코드
  - [ ] 사용자 정보 조회 API 테스트코드
  - [ ] PR 리뷰

### etc.
- [ ] 프리온보딩 프론트엔드 챌린지 사전 미션 [(영상)](https://www.youtube.com/watch?v=8aGhZQkoFbQ)

**Comment by ooheunda** [comment]
이런 날도... 있는거제 ^ㅡ^
