### ISSUE TITLE
🥷🏿 [TODO] 2024-09-05

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#12]
쉬는시간인데 ye 얘기중

## Schedule

- **`13:00 ~ 14:00` 프리온보딩 인턴십 회의 (오프라인)**
- **`14:00 ~ 17:00` 프리온보딩 인턴십 강의 (오프라인)**
- **`17:00 ~ 18:00` 프리온보딩 인턴십 멘토링 (오프라인)**
- **`21:00 ~ 26:30` KDTH 기획 회의 (온라인, 젭)**

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- 과제
  - [ ] 사용자 설정 업데이트 API 테스트코드
  - [ ] 사용자 정보 조회 API 테스트코드

### etc.
- [x] KDTH 2번, 5번 작성
- [x] SWTH 예상 질문 정리
- [ ] 프리온보딩 프론트엔드 챌린지 사전 미션 [(영상)](https://www.youtube.com/watch?v=8aGhZQkoFbQ)
- [x] 이동 시간 활용해 [책](https://product.kyobobook.co.kr/detail/S000001033125) 읽기
