### ISSUE TITLE
🐸 [TODO] 2024-09-06

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#13]
갓.생.예.감.

## Schedule

- **`10:00 ~ 10:30` 프리온보딩 인턴십 회의 (온라인, 디스코드)**
- **`10:00 ~ 16:30` SWTH 본선 (오프라인)**
- **`15:00 ~ 17:00` 프리온보딩 인턴십 커리어코칭 (온라인, 줌)** <- 못봄

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅 

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- 이전 과제
  - [x] 사용자 설정 업데이트 API 테스트코드
  - [x] 사용자 정보 조회 API 테스트코드
- 과제
  - [x] ERD
  - [ ] API 명세

### etc.
- [x] 프리온보딩 프론트엔드 챌린지 사전 미션 [(영상)](https://www.youtube.com/watch?v=8aGhZQkoFbQ)

**Comment by jis-kim** [comment]
헉 다은님 프론트도 생각있으신가요?!

**Comment by ooheunda** [comment]
@jis-kim 우와 지수님이다ㅋㅋㅋㅋㅋㅋㅋ🙈 저 [챌린지](https://www.wanted.co.kr/events/pre_challenge_fe_25)가 프론트엔드긴한데 이벤트 루프가 주제길래 신청해봤슴니다... 프론트는... 정말 생각만 있는 상태...
