### ISSUE TITLE
👀 [TODO] 2024-09-09

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#15]
업보의 날이다~!

## Schedule

- **`10:30 ~ 11:30` 프리온보딩 인턴십 회의 (온라인, 디스코드)**
- **`15:00 ~ 17:00` 프리온보딩 인턴십 커리어코칭 특강 (온라인, 줌)**
- **`20:00 ~ 23:00` 프리온보딩 백엔드 챌린지 9월 (온라인, 줌)**

### Routine
- [x] 알고리즘 1시간
- [ ] 블로깅 

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- [ ] 3주차 수업 복습...^^
- 과제
  - [x] 이슈/PR 템플릿 설정
  - [x] 이슈 발행

### etc.
