### ISSUE TITLE
👀 [TODO] 2024-09-10

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#16]
업보day2

## Schedule

- **`13:00 ~ 14:00` 프리온보딩 인턴십 회의 (오프라인)**
- **`14:00 ~ 17:00` 프리온보딩 인턴십 강의 (오프라인)**

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- 과제
  - [ ] https://github.com/ooheunda/aletheia/issues/1
  - [ ] https://github.com/ooheunda/aletheia/issues/2

### etc.
- [x] 이동 시간 활용해 [책](https://product.kyobobook.co.kr/detail/S000001033125) 읽기
