### ISSUE TITLE
☕️ [TODO] 2024-08-26

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#2]
오늘 스벅 할인해서 스벅 갈거라 커피

## Schedule

- **`10:30` 프리온보딩 인턴십 코드리뷰 (온라인, 디스코드)**
- **`12:00` 해커톤 최종 회의 (온라인, 슬랙)**
- **`17:00` 해커톤 예선 결과물 제출 마감**
- **`20:00` 프리온보딩 인턴십 코드리뷰 (온라인, 디스코드)**

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅

### Hackathon
- [x] 회의 전에 기획서 검토
- [x] Infra Architectrue 이미지 한 장으로 만들기
- [x] ERD 최종 확인

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [x] [게시물 목록 조회 API](https://github.com/INgandle/social-feed-hub/issues/12) 로직 작성
- [x] [게시물 상세 조회 API](https://github.com/INgandle/social-feed-hub/issues/13) 가드 적용하고 마무리

### etc.
- [x] [Magpie](https://www.youtube.com/watch?v=DKyWzW9WXic) 질릴때까지 듣기
