### ISSUE TITLE
🥯 [TODO] 2024-08-27

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#3]
베이글 먹고 싶은거 참는중 (사실 토요일에 먹음)

## Schedule

- **`12:00` KDT 해커톤 신청 마감**
- **`13:00 ~ 14:00` 프리온보딩 인턴십 과제분석 (오프라인)**
- **`14:00 ~ 17:00` 프리온보딩 인턴십 (오프라인)**
- **`20:00` KDT 해커톤 첫 회의 (온라인, 젭)**

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 오늘(27일) 수업 복습
- 지나간 과제
  - [x] 어제 리뷰 받은 부분 반영
  - [ ] 스웨거 적용
- 이번 과제
  - [x] 만나기 전에 과제 요구사항 정독
  - [x] 맡은 부분 API 명세 작성

### etc.
- [x] 이동 시간 활용해 [책](https://product.kyobobook.co.kr/detail/S000001033125) 읽기
- [ ] 제발 런데이 가기
- [x] [I Was Just a Kid](https://www.youtube.com/watch?v=yEyMGqsV3_A) 질릴때까지 듣기
