### ISSUE TITLE
🥯 [TODO] 2024-08-28

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#4]
진짜 베이글 너무 먹고싶다...

## Schedule

- **`10:30 ~ 12:10` 프리온보딩 인턴십 회의 (온라인, 디스코드)**
- **`12:10 ~ 13:10` KDT 해커톤 기획 회의 중간참여 (온라인, 젭)**
- **`15:30 ~ 16:20` KDT 해커톤 매니저님과 팀 미팅 (온라인, 젭)**

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 어제(27일) 수업 복습
- 지나간 과제
  - [x] 새롭게 리뷰 받은 부분 수정
  - [ ] 스웨거 적용
- 이번 과제
  - [ ] 맡은 부분 이슈 발행하기
  - [x] 기능 정의 제대로
  - [x] PR 리뷰

### etc.

**Comment by ooheunda** [comment]
베이글 먹었음...
