### ISSUE TITLE
🥑 [TODO] 2024-08-29

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#5]
아침으로 어제 먹고 남은 아보카도 베이글 먹음

## Schedule

- **`13:00 ~ 14:00` 프리온보딩 인턴십 과제분석 (오프라인)**
- **`14:00 ~ 17:00` 프리온보딩 인턴십 강의 (오프라인)**
- **`17:00 ~ 18:00` 프리온보딩 인턴십 과제분석 (오프라인)**

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- [x] 1주차 보강
- 지나간 과제
  - [ ] 스웨거 적용
- 이번 과제
  - [x] 맡은 부분 이슈 발행하기
  - [x] 맛집 리뷰 생성 API 구현

### etc.
- [x] 이동 시간 활용해 [책](https://product.kyobobook.co.kr/detail/S000001033125) 읽기
