### ISSUE TITLE
👩‍💻 [TODO] 2024-08-30

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#6]
내일 놀려면 열심히 해야됨

## Schedule

- **`10:00 ~ 11:00` 프리온보딩 인턴십 회의 (온라인, 디스코드)**
- **`15:00 ~ 17:00` 프리온보딩 인턴십 커리어 코칭 특강 (온라인, 줌)**
- **`21:00 ~ 22:00` 프리온보딩 인턴십 회의 (온라인, 디스코드)**

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- 과제
  - [x] 멘토님께 리뷰 도메인 관련 질문 남기기
  - [ ] 리뷰 생성 API TODOs 해결
  - [x] 사용자 정보 조회 API 구현
  - [x] 사용자 설정 업데이트 API 구현

### etc.
