### ISSUE TITLE
🥳 [TODO] 2024-08-31

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#7]
오늘 칭긔 생일~~~

## Schedule

- **[YOUTHCON'24](https://frost-witch-afb.notion.site/YOUTHCON-24-49177aa1b828435f98046912c6debc78) 골라듣기 (온라인, 줌)**
- **`17:00 ~ 22:00` 약속**

### Routine
- [x] 알고리즘 1시간
- [ ] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- 과제
  - [x] 사용자 API들에 스웨거 적용
  - [x] 사용자 PR 날리기
  - [x] 리뷰 생성 API TODOs 해결
  - [ ] 리뷰 생성 API 테스트 코드 지선생에게 부탁하고 공부하기

### etc.
- [x] 이동 시간 활용해 [책](https://product.kyobobook.co.kr/detail/S000001033125) 읽기
