### ISSUE TITLE
9️⃣ [TODO] 2024-09-01

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#8]
벌써9월이라니말도않되

## Schedule

- **`17:00 ~ 18:40` 프리온보딩 인턴십 코드리뷰 (온라인, 디스코드)**
- **`20:00 ~ 22:30` KDT 해커톤 기획 회의 (온라인, 젭)**

### Routine
- [ ] 알고리즘 1시간
- [ ] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- 과제
  - [x] 리뷰 생성 API 스웨거 적용
  - [x] 코드리뷰 받은 부분 반영
  - [ ] 리뷰 생성 API 테스트 코드 지선생에게 부탁하고 공부하기

### SWT-Hackathon
- [x] 서비스 기능 설명 대본 작성 (3분)
- [x] 장표 배치 생각해보기
- [ ] 시간 남으면 서비스 아키텍처 다듬기

### etc.
