### ISSUE TITLE
👩‍💻 [TODO] 2024-09-02

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/ooheunda.github.io#9]
오늘왠지갓생살것같은느낌이.

## Schedule

- **`16:00 ~ 17:20` 프리온보딩 인턴십 코드리뷰 (온라인, 디스코드)**
- **`20:00 ~ 23:00` 프리온보딩 백엔드 챌린지 9월 (온라인, 줌)**

### Routine
- [ ] 알고리즘 1시간
- [x] 블로깅

### Pre-Onboarding
- [ ] 1주차 수업 복습
- [ ] 2주차 수업 복습
- 과제
  - [x] 리뷰 생성 API 테스트 코드 지선생에게 부탁하고 공부하기
  - [ ] 사용자 설정 업데이트 API 테스트코드
  - [ ] 사용자 정보 조회 API 테스트코드
  - [x] RDS 연결 안되는거 해결
  - [x] AWS IAM 만들고 EC2, RDS 인스턴스 생성

### Hackathon
- [x] SWT) 최종 발표 자료 검토
- [x] KDT) 기획서 검토

### etc.
- [x] 스파르타 AWS 강의 IAM 부분
- 프리온보딩 백엔드 챌린지
  - [ ] 사전 미션 1 [(영상)](https://www.youtube.com/watch?v=THLwpz-0g-U)
  - [ ] 사전 미션 2 [(영상)](https://www.youtube.com/watch?v=fhNpjPr-f54)
- [ ] 프리온보딩 프론트엔드 챌린지 사전 미션 [(영상)](https://www.youtube.com/watch?v=8aGhZQkoFbQ)
